#!groovy

// Generated by IBM TransformationAdvisor
// Fri Jul 05 01:02:24 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'servletsample'
    mvnCommands = '--version'
    test='false'
}